### PR TITLE
Add minimal CLI suitable for running the formatter

### PR DESCRIPTION
**Pull request by thomashoneyman**
Adds a basic CLI we can use to run the formatter during development. I've kept dependencies minimal until we know exactly what the CLI should do.

### CODE REVIEW

**Comment by colinwahl** [comment]
In the future if we start adding a lot more CLI arguments, we should probably look at using [clap](https://github.com/clap-rs/clap)

**Comment by colinwahl** [comment]
Instead of using `io::Result`, I think it's easier to [box errors](https://doc.rust-lang.org/rust-by-example/error/multiple_error_types/boxing_errors.html) so that we can use `?` syntax for the different functions that may error instead of using `.expect` - for example, if we swapped all `io::Result` to 

`type Result<T> = std::result::Result<T, Box<dyn error::Error>>;`

then later lines can just be like

`for entry in glob::glob(pattern)?`

**Review by colinwahl — APPROVED** [review]
Small nits - looks good otherwise!

**Comment by thomashoneyman** [comment]
@colinwahl Is my latest commit more what you were thinking?

**Pull request merged**
